### ISSUE TITLE
Write tests for hotfix and revisit use of resolveDependencyPath

### ISSUE THREAD

**Issue by mrjoelkemp** [dependents/node-filing-cabinet#24]
* Ref https://github.com/dependents/node-filing-cabinet/pull/23
* Ref https://travis-ci.org/pahen/madge/jobs/157012487

Look into how that gets triggered from madge. Is there a file extension for jsx that we're not supporting here?

**Comment by pahen** [comment]
The build is ok now. But this was the failing test: https://github.com/pahen/madge/blob/master/test/jsx.js
