### ISSUE TITLE
tsLookup only resolves using AMD module system

### ISSUE THREAD

**Issue by netanelgilad** [dependents/node-filing-cabinet#34]
https://github.com/dependents/node-filing-cabinet/blob/796afc98be30097540e32afbc947640ba6220429/index.js#L151-L157

Currently the tsLookup function only resolves using the AMD module system. Any specific reason for that? or can we find a way to make it configurable?

Thanks for the great lib! 🍻

**Comment by mrjoelkemp** [comment]
I was hacking together support without a lot of time for the effort. There must be a better way. Would be great to avoid sniffing the module type (es6, amd, cjs) to determine the proper configuration. Is there an es6 config value that would suffice? I imagine non-es6 module types are unlikely to use this lib; we can always add the module type sniff (making sure to reuse asts) if need be.

**Comment by amitdahan** [comment]
+1 for module type sniff

**Comment by claudineioj** [comment]
@mrjoelkemp any idea on when it might be released?
It didn't work properly on my typescript files since I use a webpack alias in my imports.

**Comment by mrjoelkemp** [comment]
Thanks for following up. I haven't looked into it since the issue was created. I'm open to a PR that fixes the issue. Any help is appreciated.
