### ISSUE TITLE
Upgrade Typescript

### ISSUE THREAD

**Issue by GabrielCastro** [dependents/node-filing-cabinet#55]
Typescript 3.0.0 has been release with no breaking changes
Upgrading typescript to `^2.4.2 || ^3.0.1` should work best

**Comment by mrjoelkemp** [comment]
Thanks for filing @GabrielCastro. This was done in https://github.com/dependents/node-filing-cabinet/pull/61/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R58.
