### ISSUE TITLE
1.14.4 contains a breaking change

### ISSUE THREAD

**Issue by michaelwittig** [dependents/node-filing-cabinet#60]
Hi,

version 1.14.4 starts to use language features such as `const` which is not a bug fix more a breaking change. Was this intended? I also see that a version 2.y.z now exists which might be better suited to contain such changes.

I'm not a direct user of filing-cabinet, instead `madge -> dependency-tree -> filing-cabinet` and dependency-tree sets this dependency `filing-cabinet@^1.9.0`

**Comment by mrjoelkemp** [comment]
Hey @michaelwittig. Thanks for filing the issue; the visibility is really helpful. You're totally right that breaking changes slipped in. Sorry about that.

The minimum node version was set to 6 back in January (where I should have done a major bump but didn't). The es6 changes were a patch given that the node version was already set to 6.

If you have ideas on how to rectify the issue, please let me know.

**Comment by michaelwittig** [comment]
As far as I can see, the last version before the engine bump was 1.13.0. The only idea I have at the moment is to release the code as it was for version 1.13.0 as something > 1.14.4 and < 2.0.0 but that could also cause some confusion depending on the changes that happened after 1.13.0 but before 2.0.0

**Comment by mrjoelkemp** [comment]
Thanks for your thoughts @michaelwittig. Agreed that things start to get a bit funky going back in time. I hope the breaking change is not a massive inconvenience to consumers. 

I'll try to be more diligent moving forward. I'll close this issue since the original question has been addressed. Thanks again for contributing.
