### ISSUE TITLE
Issue in tsConfig options resolving

### ISSUE THREAD

**Issue by vansosnin** [dependents/node-filing-cabinet#85]
Hello!

Noticed that [method](https://github.com/dependents/node-filing-cabinet/blob/master/index.js#L214) that is being used to resolve ts config compiler options not working properly if passed config has `extends` field.

`const {options} = ts.convertCompilerOptionsFromJson(tsConfig.compilerOptions);`

Maybe try using `parseJsonConfigFileContent` from TS Compiler API? It resolves `CompilerOptions` well, though a bit more complicated in use: you need to create an instance of `ParseConfigHost`. It can be done like [here](https://stackoverflow.com/questions/53804566/how-to-get-compileroptions-from-tsconfig-json).

**Comment by vansosnin** [comment]
Wrote red test. Using `parseJsonConfigFileContent` did not work. Have no idea now about how to resolve extending TS config. Any thoughts?

**Comment by vansosnin** [comment]
Okay, now it seems working. Can someone check the PR? @mrjoelkemp maybe?

**Comment by mrjoelkemp** [comment]
Merged and released. Thanks again!
